routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('pdf', function () {
    $pdf = PDF::loadView('vista');
    return $pdf->download('factura.pdf');
});





use MappingManagementSystem\Exports\BooksExport;//invocamos el export de BOOKS  
use Maatwebsite\Excel\Facades\Excel;

#// // // Route::get('exportarlibros', function () {
#// // //     return Excel::download(new BooksExport, 'books.xlsx');
#// // // });
 

 


// #########################--ADMINISTRACIÓN DE BOOKS--#####################
Route::resource('books' , 'bookController');   //asignamos las rutas automaticamente para que sea despachada por medio del controlador
Route::get('exportar', 'bookController@excel') ;// ruta para la exportacion dee libros en excell
Route::get('pdf', 'bookController@pdf') ;// ruta para la exportacion dee libros en excell
Route::get('books/{slug}/show', 'bookController@show') ->name('books.show');// ruta para la exportacion dee libros en excell
Route::get('books/{slug}/edit', 'bookController@edit') ->name('books.edit');// ruta para la exportacion dee libros en excell
Route::DELETE('books/{slug}/destroy', 'bookController@destroy') ->name('books.destroy');// ruta para la exportacion dee libros en excell
// Route::get('pdf', 'bookController@pdf') ;// ruta para la exportacion dee libros en excell

// #########################--ADMINISTRACIÓN DE USUARIOS--#####################


// // #########################--ADMINISTRACIÓN DE USUARIOS--#####################
// Route::get  ('/usuarios'                        , 'UserController@index');   
// Route::get  ('/usuarios/editar/{id}'            , 'UserController@edit');   
// // #########################--ADMINISTRACIÓN DE USUARIOS--#####################



// // #########################--ADMINISTRACIÓN DE PAISES--########################
Route::get  ('/paises'                          , 'CountriesController@index');   
Route::get  ('/paises/new/'                     , 'CountriesController@new');
// Route::get ('/paises/create'                   , 'PaisesController@create');
Route::post ('/paises/create'                   , 'CountriesController@create');
// // #########################--ADMINISTRACIÓN DE PAISES--#########################



// #########################--RUTAS DEL SISTEMA--###############################
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
// #########################--RUTAS DEL SISTEMA--###############################

app/Book.php
<?php

namespace MappingManagementSystem;

use Illuminate\Database\Eloquent\Model;
Use Cviebrock\EloquentSluggable\Sluggable;
 



class Book extends Model {

    use Sluggable;

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable() {

        // el campo se va a llenar cuando se ingrese informacion en el camppo "tittle" (la fuente puede ser cualquier campo)
        return [ 'slug' => [ 'source' => 'tittle','save_to' => 'slug'] ];
        
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id','tittle', 'author','slug',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        //
    ];
}

 

app/Http/Controllers/BookController.php
<?php

namespace MappingManagementSystem\Http\Controllers;
// use MappingManagementSystem\Http\Controllers\Controller;
use MappingManagementSystem\Book;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

// uso de la paginacion
use Illuminate\Pagination\Paginator;
// uso de la paginacion

// uso del exportador de excel
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Facades\Excel;
use Maatwebsite\Excel\Concerns\Exportable;
use MappingManagementSystem\Exports\BooksExport;
// uso del exportador de excel

// uso de los slugs
Use Cviebrock\EloquentSluggable\Sluggable;
// uso de los slugs

use MappingManagementSystem\Http\Requests\books\BooksStoreRequest;
use MappingManagementSystem\Http\Requests\books\BooksUpdateRequest;

 
class BookController extends Controller {

    use Exportable;


    public function excel( ) {
        

        
        return (new BooksExport)->download('invoices.xlsx');
        // return redirect()->action('bookController@create');
    }
 

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function pdf() {

        $books = Book::all();

        $pdf = \PDF::loadView('books/vista', ['books' => $books]);
        return $pdf->stream('factura.pdf');

    }

    public function index() {

        $books = Book::orderBy('id','desc')->paginate(10);// se trae la información del base de datos, se ordena por id de forma ascendente y se pasa la paginación
        return view('books.index', [ 'books' => $books ] );// se retorna la vista y se le manda el array de la información buscada

    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
        
        return view('books.create');// se retorna la vista con el formulario para crear el nuevo articulo

    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BooksStoreRequest $request){

        $validatedData = $request->validate([ //validamos que requiera el contenido para enviar el formulario
            'tittle' => 'required| max:10',
            'author' => 'required| max:10',
        ]);

        // se registra los  datos que se reciven por el request

        Book::create($validatedData) ;

        return redirect('books/')->with('Success','The new book was  added successfully!'); 
        
    }


    /**
     * Display the specified resource.
     *
     * @param  \MappingManagementSystem\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(  $slug)
    {
        
        $book = book::where('slug','=',$slug)->FirstOrFail();
       
        // return view('books.edit', [ 'book' => $book ] );
        return view('books.show',   [ 'book' => $book ]);
    
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \MappingManagementSystem\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit($slug){
        
        $book = book::where('slug','=',$slug)->FirstOrFail();
        
        // return view('books.edit', [ 'book' => $book ] );
        return view('books.edit',  compact('book'));
    }


    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \MappingManagementSystem\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(BooksUpdateRequest $request, Book $book)
    {
        $request->validate([
            'tittle' => 'required',
            'author' => 'required',
        ]);
  
        if ($book->update($request->all())){
            return redirect()->route('books.index')->with('success','Book updated successfully');
        }else{
            return redirect()->route('books.index')->with('alert',' Problems updating book');
        }
  
       
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  \MappingManagementSystem\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy($slug){
        
        $book = book::where('slug','=',$slug)->FirstOrFail();
        if ($book->delete()){
            return redirect()->route('books.index')->with('success','Book deleted successfully');
        }else{
            return redirect()->route('books.index')->with('alert',' Problems deleting  book');
        }
  
    }
}

resources/views/books/create.blade.php
 
@extends ('layouts/dashboardLayout2')<!-- Extendemos la plantiya de layout principal -->
     
@section('content') 


<br>
<br>
<br>

    <div class="container  ">       
        <div class="row ">
            
            <form class="col-5 card p-5 mx-auto" method="POST" action="{{route('books.store')}}">
                
                <p> <h3 class="text-center">Create a New Book</h3></p>

                @csrf <!-- se pasa un token por debajo para evitar los ataques CSRF -->
                              
                <div class="form-group ">
                    <label for="pais">Tittle: </label>
                    <input type="text" name="tittle" class="form-control" id="tittle" placeholder="ingrese el titulo">
                </div>

                <div class="form-group">
                    <label for="author">Author:</label>
                    <input type="text" name="author"  class="form-control" id="author" placeholder="ingrese el author ">
                </div>
                 
                <div class="btn-group btn-group-sm">
                    <button type="submit" class="btn btn-primary ">Submit</button>
                    <a class="btn btn-secondary  " href="{{ route('books.index') }}"><i class="fas fa-undo"></i> Back</a>
                </div>
                
               

            </form>
                
        </div>
    </div>

@endsection

resources/views/books/edit.blade.php
 
@extends ('layouts/dashboardLayout2')<!-- Extendemos la plantiya de layout principal -->
     
@section('content') 


<br>
<br>
<br>

    <div class="container  ">       
        <div class="row ">
            
            <form class="col-5 card p-5 mx-auto" action="{{route('books.update', $book->id)}}" method="POST" >
                
                <p> <h3 class="text-center">Edit a This Book</h3></p>
                @method('put')<!-- se le pasa el meotodo PUT para el update -->
                @csrf <!-- se pasa un token por debajo para evitar los ataques CSRF -->
                              
                <div class="form-group ">
                    <label for="pais">Tittle: </label>
                    <input type="text" name="tittle" class="form-control" id="tittle" placeholder="ingrese el titulo" value="{{$book->tittle}}">
                </div>

                <div class="form-group">
                    <label for="author">Author:</label>
                    <input type="text" name="author"  class="form-control" id="author" placeholder="ingrese el author " value="{{$book->author}}">
                </div>
                 
                 
                <div class="btn-group   btn-group-lg" style=" ">
                    <button class="btn btn-primary btn-lg"  type="submit"  >Submit</button>
                    <a      class="btn btn-secondary btn-lg" href="{{ route('books.index') }}"><i class="fas fa-undo"></i> Back</a>
                </div>
                 
                 
            </form>
                
        </div>
    </div>

@endsection

resources/views/books/show.blade.php
 
@extends ('layouts/dashboardLayout2')<!-- Extendemos la plantiya de layout principal -->
     
@section('content') 


<br>
<br>
<br>

    <div class="container  ">       
        <div class="row ">
            
            <div class="col-5 card p-5 mx-auto"   >
                
                <p> <h3 class="text-center">Showing this Book</h3></p>
                @method('put')<!-- se le pasa el meotodo PUT para el update -->
                @csrf <!-- se pasa un token por debajo para evitar los ataques CSRF -->
                              
                <div class="form-group ">
                    <label for="pais"><strong>Tittle:</strong> </label>
                    <input type="text" name="tittle" class="form-control" id="tittle"  value="{{$book->tittle}}"  readonly=”readonly” >
                </div>

                <div class="form-group">
                    <label for="author"><strong>Author:</strong></label>
                    <input type="text" name="author"  class="form-control" id="author"  value="{{$book->author}}"  readonly=”readonly” >
                </div>
                 
                 
                <div class="btn-group btn-group-sm">
                    <a class="btn btn-info" href="{{ route('books.index') }}"><i class="fas fa-undo"></i> Return Back</a>
                </div>
                 
                 
            </div>
                
        </div>
    </div>

@endsection

resources/views/books/vista.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">


  
  
    @foreach($books as $book )
        <ul class=" alert alert-success alert-dismiss">
            <li class="">{{ $book->id }}</li>
            <li class="">{{ $book->tittle }} </li>
            <li class=""> {{$book->author}} </li>
        </ul>
       
    @endforeach


  
</div>

</body>
</html>